method: conv_onet
data:
  dataset: 'kitti360'
  dim: 3
  padding: 0.1
  classes: null
  input_type: pointcloud
  partial_path: /home/sbharadwaj/dataset/4096-8192-kitti360
  path: /home/sbharadwaj/dataset/4096-8192-kitti360-semantic
  train_split: train
  val_split: val
  pose_path: /home/sbharadwaj/dataset/data_poses
model:
  encoder: pointnet_local_pool
  encoder_kwargs:
    hidden_dim: 64
    plane_type: 'grid'
    grid_resolution: 64
    unet3d: True
    unet3d_kwargs:
      num_levels: 4
      f_maps: 64
      in_channels: 64
      out_channels: 64
  decoder: None
  c_dim: 64
training:
  out_dir:  out/voxels_semantic/exp1/
  batch_size: 4
  print_every: 5
  n_workers: 8
  n_workers_val: 4
  eval_sample: false
  epochs: 150

