method: conv_onet
data:
  dataset: 'kitti360'
  classes: null
  input_type: pointcloud
  path: home/bharadwaj/implementations/DATA/
  dim: 3
  pointcloud_n: 100000
  pointcloud_noise: 0.005
  points_subsample: 2048
  train_split: /home/bharadwaj/data_prep/data/train/2013_05_28_drive_0000_sync_000001_000800/
  val_split: /home/bharadwaj/data_prep/data/test/2013_05_28_drive_0000_sync_000801_001000/
  test_split: /home/bharadwaj/data_prep/data/test/2013_05_28_drive_0000_sync_000801_001000/
model:
  encoder: pointnet_local_pool
  encoder_kwargs:
    hidden_dim: 64
    plane_type: 'grid'
    grid_resolution: 64
    unet3d: True
    unet3d_kwargs:
      num_levels: 4
      f_maps: 64
      in_channels: 64
      out_channels: 64
  decoder: None
  c_dim: 64
training:
  out_dir:  out/voxels/bin-vox-final/
  batch_size: 4
  model_selection_metric: iou
  model_selection_mode: maximize
  print_every: 5
  visualize_every: 10000
  validate_every: 10000
  checkpoint_every: 2000
  backup_every: 10000
  n_workers: 8
  n_workers_val: 4
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
generation:
  vis_n_outputs: 2
  refine: false
  n_x: 128
  n_z: 1
